[package]
name = "black-hole-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = { version = "1.23.2", features = ["derive"] }
env_logger = "0.11.8"
image = "0.25.8"
log = "0.4.28"
macroquad = "0.4.14"
wgpu = { version = "26.0.1", features = ["spirv"] }
