[package]
name = "black-hole-sim"
version = "0.1.0"
edition = "2024"

[dependencies]
macroquad = "0.4.14"
ndarray = "0.16.1"
num = "0.4.3"
pixels = "0.15.0"
tokio = { version = "1.47.1", features = ["full"] }
winit = "0.30.12"
